name: PR Check

on:
  - pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./app-demo
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run:  |
          pip3 install -r requirements.txt

      - name: Run Test
        run:  |
          pytest  test/test.py